import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>LESKOFI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.logo_container}>
          <Image
            src="/images/logo-leskofi.webp"
            alt="Logo LESKOFI"
            fill
            // width={1498}
            // height={800}
            className={styles.logo_image}
          />
        </div>
        <div className={styles.content_container}>
          <span className={styles.content_first}>COMING SOON</span>
        </div>
      </main>
    </>
  );
}
